name: Generate Codebase Diagram

on:
  push:
    branches: [main]
  workflow_dispatch: # lets you run manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: diagram.svg
