name: Generate Codebase Diagram

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Generate diagram.svg
      - name: Generate diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: diagram.svg

      # Step 3: Commit and push updated diagram
      - name: Commit diagram
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add diagram.svg
          git commit -m "Update diagram.svg" || echo "No changes to commit"
          git push
